/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSettingsLayoutRouteImport } from './routes/settings/_settingsLayout'
import { Route as DashboardDashboardLayoutRouteImport } from './routes/dashboard/_dashboardLayout'
import { Route as AuthTwoFactorRouteImport } from './routes/auth/two-factor'
import { Route as SettingsSettingsLayoutIndexRouteImport } from './routes/settings/_settingsLayout/index'
import { Route as DashboardDashboardLayoutIndexRouteImport } from './routes/dashboard/_dashboardLayout/index'
import { Route as SettingsSettingsLayoutTeamsRouteImport } from './routes/settings/_settingsLayout/teams'
import { Route as SettingsSettingsLayoutShortcutsRouteImport } from './routes/settings/_settingsLayout/shortcuts'
import { Route as SettingsSettingsLayoutProfileRouteImport } from './routes/settings/_settingsLayout/profile'
import { Route as SettingsSettingsLayoutAuthenticationRouteImport } from './routes/settings/_settingsLayout/authentication'
import { Route as DashboardDashboardLayoutProfileRouteImport } from './routes/dashboard/_dashboardLayout/profile'
import { Route as DashboardDashboardLayoutExamplesRouteImport } from './routes/dashboard/_dashboardLayout/examples'
import { Route as DashboardDashboardLayoutPostsIndexRouteImport } from './routes/dashboard/_dashboardLayout/posts/index'
import { Route as DashboardDashboardLayoutPostsNewRouteImport } from './routes/dashboard/_dashboardLayout/posts/new'
import { Route as DashboardDashboardLayoutPostsPostIdRouteImport } from './routes/dashboard/_dashboardLayout/posts/$postId'
import { ServerRoute as ApiTrpcSplatServerRouteImport } from './routes/api.trpc.$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const SettingsRouteImport = createFileRoute('/settings')()
const DashboardRouteImport = createFileRoute('/dashboard')()
const rootServerRouteImport = createServerRootRoute()

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSettingsLayoutRoute = SettingsSettingsLayoutRouteImport.update({
  id: '/_settingsLayout',
  getParentRoute: () => SettingsRoute,
} as any)
const DashboardDashboardLayoutRoute =
  DashboardDashboardLayoutRouteImport.update({
    id: '/_dashboardLayout',
    getParentRoute: () => DashboardRoute,
  } as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/auth/two-factor',
  path: '/auth/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSettingsLayoutIndexRoute =
  SettingsSettingsLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsSettingsLayoutRoute,
  } as any)
const DashboardDashboardLayoutIndexRoute =
  DashboardDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const SettingsSettingsLayoutTeamsRoute =
  SettingsSettingsLayoutTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => SettingsSettingsLayoutRoute,
  } as any)
const SettingsSettingsLayoutShortcutsRoute =
  SettingsSettingsLayoutShortcutsRouteImport.update({
    id: '/shortcuts',
    path: '/shortcuts',
    getParentRoute: () => SettingsSettingsLayoutRoute,
  } as any)
const SettingsSettingsLayoutProfileRoute =
  SettingsSettingsLayoutProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => SettingsSettingsLayoutRoute,
  } as any)
const SettingsSettingsLayoutAuthenticationRoute =
  SettingsSettingsLayoutAuthenticationRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => SettingsSettingsLayoutRoute,
  } as any)
const DashboardDashboardLayoutProfileRoute =
  DashboardDashboardLayoutProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const DashboardDashboardLayoutExamplesRoute =
  DashboardDashboardLayoutExamplesRouteImport.update({
    id: '/examples',
    path: '/examples',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const DashboardDashboardLayoutPostsIndexRoute =
  DashboardDashboardLayoutPostsIndexRouteImport.update({
    id: '/posts/',
    path: '/posts/',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const DashboardDashboardLayoutPostsNewRoute =
  DashboardDashboardLayoutPostsNewRouteImport.update({
    id: '/posts/new',
    path: '/posts/new',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const DashboardDashboardLayoutPostsPostIdRoute =
  DashboardDashboardLayoutPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const ApiTrpcSplatServerRoute = ApiTrpcSplatServerRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/tos': typeof TosRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/dashboard': typeof DashboardDashboardLayoutRouteWithChildren
  '/settings': typeof SettingsSettingsLayoutRouteWithChildren
  '/dashboard/examples': typeof DashboardDashboardLayoutExamplesRoute
  '/dashboard/profile': typeof DashboardDashboardLayoutProfileRoute
  '/settings/authentication': typeof SettingsSettingsLayoutAuthenticationRoute
  '/settings/profile': typeof SettingsSettingsLayoutProfileRoute
  '/settings/shortcuts': typeof SettingsSettingsLayoutShortcutsRoute
  '/settings/teams': typeof SettingsSettingsLayoutTeamsRoute
  '/dashboard/': typeof DashboardDashboardLayoutIndexRoute
  '/settings/': typeof SettingsSettingsLayoutIndexRoute
  '/dashboard/posts/$postId': typeof DashboardDashboardLayoutPostsPostIdRoute
  '/dashboard/posts/new': typeof DashboardDashboardLayoutPostsNewRoute
  '/dashboard/posts': typeof DashboardDashboardLayoutPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/tos': typeof TosRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/dashboard': typeof DashboardDashboardLayoutIndexRoute
  '/settings': typeof SettingsSettingsLayoutIndexRoute
  '/dashboard/examples': typeof DashboardDashboardLayoutExamplesRoute
  '/dashboard/profile': typeof DashboardDashboardLayoutProfileRoute
  '/settings/authentication': typeof SettingsSettingsLayoutAuthenticationRoute
  '/settings/profile': typeof SettingsSettingsLayoutProfileRoute
  '/settings/shortcuts': typeof SettingsSettingsLayoutShortcutsRoute
  '/settings/teams': typeof SettingsSettingsLayoutTeamsRoute
  '/dashboard/posts/$postId': typeof DashboardDashboardLayoutPostsPostIdRoute
  '/dashboard/posts/new': typeof DashboardDashboardLayoutPostsNewRoute
  '/dashboard/posts': typeof DashboardDashboardLayoutPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/tos': typeof TosRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_dashboardLayout': typeof DashboardDashboardLayoutRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/settings/_settingsLayout': typeof SettingsSettingsLayoutRouteWithChildren
  '/dashboard/_dashboardLayout/examples': typeof DashboardDashboardLayoutExamplesRoute
  '/dashboard/_dashboardLayout/profile': typeof DashboardDashboardLayoutProfileRoute
  '/settings/_settingsLayout/authentication': typeof SettingsSettingsLayoutAuthenticationRoute
  '/settings/_settingsLayout/profile': typeof SettingsSettingsLayoutProfileRoute
  '/settings/_settingsLayout/shortcuts': typeof SettingsSettingsLayoutShortcutsRoute
  '/settings/_settingsLayout/teams': typeof SettingsSettingsLayoutTeamsRoute
  '/dashboard/_dashboardLayout/': typeof DashboardDashboardLayoutIndexRoute
  '/settings/_settingsLayout/': typeof SettingsSettingsLayoutIndexRoute
  '/dashboard/_dashboardLayout/posts/$postId': typeof DashboardDashboardLayoutPostsPostIdRoute
  '/dashboard/_dashboardLayout/posts/new': typeof DashboardDashboardLayoutPostsNewRoute
  '/dashboard/_dashboardLayout/posts/': typeof DashboardDashboardLayoutPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/tos'
    | '/auth/two-factor'
    | '/dashboard'
    | '/settings'
    | '/dashboard/examples'
    | '/dashboard/profile'
    | '/settings/authentication'
    | '/settings/profile'
    | '/settings/shortcuts'
    | '/settings/teams'
    | '/dashboard/'
    | '/settings/'
    | '/dashboard/posts/$postId'
    | '/dashboard/posts/new'
    | '/dashboard/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/tos'
    | '/auth/two-factor'
    | '/dashboard'
    | '/settings'
    | '/dashboard/examples'
    | '/dashboard/profile'
    | '/settings/authentication'
    | '/settings/profile'
    | '/settings/shortcuts'
    | '/settings/teams'
    | '/dashboard/posts/$postId'
    | '/dashboard/posts/new'
    | '/dashboard/posts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/tos'
    | '/auth/two-factor'
    | '/dashboard'
    | '/dashboard/_dashboardLayout'
    | '/settings'
    | '/settings/_settingsLayout'
    | '/dashboard/_dashboardLayout/examples'
    | '/dashboard/_dashboardLayout/profile'
    | '/settings/_settingsLayout/authentication'
    | '/settings/_settingsLayout/profile'
    | '/settings/_settingsLayout/shortcuts'
    | '/settings/_settingsLayout/teams'
    | '/dashboard/_dashboardLayout/'
    | '/settings/_settingsLayout/'
    | '/dashboard/_dashboardLayout/posts/$postId'
    | '/dashboard/_dashboardLayout/posts/new'
    | '/dashboard/_dashboardLayout/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TosRoute: typeof TosRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$' | '/api/trpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$' | '/api/trpc/$'
  id: '__root__' | '/api/auth/$' | '/api/trpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiTrpcSplatServerRoute: typeof ApiTrpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/_settingsLayout': {
      id: '/settings/_settingsLayout'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsSettingsLayoutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/dashboard/_dashboardLayout': {
      id: '/dashboard/_dashboardLayout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardLayoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/two-factor': {
      id: '/auth/two-factor'
      path: '/auth/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/_settingsLayout/': {
      id: '/settings/_settingsLayout/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsSettingsLayoutIndexRouteImport
      parentRoute: typeof SettingsSettingsLayoutRoute
    }
    '/dashboard/_dashboardLayout/': {
      id: '/dashboard/_dashboardLayout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/settings/_settingsLayout/teams': {
      id: '/settings/_settingsLayout/teams'
      path: '/teams'
      fullPath: '/settings/teams'
      preLoaderRoute: typeof SettingsSettingsLayoutTeamsRouteImport
      parentRoute: typeof SettingsSettingsLayoutRoute
    }
    '/settings/_settingsLayout/shortcuts': {
      id: '/settings/_settingsLayout/shortcuts'
      path: '/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof SettingsSettingsLayoutShortcutsRouteImport
      parentRoute: typeof SettingsSettingsLayoutRoute
    }
    '/settings/_settingsLayout/profile': {
      id: '/settings/_settingsLayout/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsSettingsLayoutProfileRouteImport
      parentRoute: typeof SettingsSettingsLayoutRoute
    }
    '/settings/_settingsLayout/authentication': {
      id: '/settings/_settingsLayout/authentication'
      path: '/authentication'
      fullPath: '/settings/authentication'
      preLoaderRoute: typeof SettingsSettingsLayoutAuthenticationRouteImport
      parentRoute: typeof SettingsSettingsLayoutRoute
    }
    '/dashboard/_dashboardLayout/profile': {
      id: '/dashboard/_dashboardLayout/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardDashboardLayoutProfileRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/dashboard/_dashboardLayout/examples': {
      id: '/dashboard/_dashboardLayout/examples'
      path: '/examples'
      fullPath: '/dashboard/examples'
      preLoaderRoute: typeof DashboardDashboardLayoutExamplesRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/dashboard/_dashboardLayout/posts/': {
      id: '/dashboard/_dashboardLayout/posts/'
      path: '/posts'
      fullPath: '/dashboard/posts'
      preLoaderRoute: typeof DashboardDashboardLayoutPostsIndexRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/dashboard/_dashboardLayout/posts/new': {
      id: '/dashboard/_dashboardLayout/posts/new'
      path: '/posts/new'
      fullPath: '/dashboard/posts/new'
      preLoaderRoute: typeof DashboardDashboardLayoutPostsNewRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/dashboard/_dashboardLayout/posts/$postId': {
      id: '/dashboard/_dashboardLayout/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/dashboard/posts/$postId'
      preLoaderRoute: typeof DashboardDashboardLayoutPostsPostIdRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface DashboardDashboardLayoutRouteChildren {
  DashboardDashboardLayoutExamplesRoute: typeof DashboardDashboardLayoutExamplesRoute
  DashboardDashboardLayoutProfileRoute: typeof DashboardDashboardLayoutProfileRoute
  DashboardDashboardLayoutIndexRoute: typeof DashboardDashboardLayoutIndexRoute
  DashboardDashboardLayoutPostsPostIdRoute: typeof DashboardDashboardLayoutPostsPostIdRoute
  DashboardDashboardLayoutPostsNewRoute: typeof DashboardDashboardLayoutPostsNewRoute
  DashboardDashboardLayoutPostsIndexRoute: typeof DashboardDashboardLayoutPostsIndexRoute
}

const DashboardDashboardLayoutRouteChildren: DashboardDashboardLayoutRouteChildren =
  {
    DashboardDashboardLayoutExamplesRoute:
      DashboardDashboardLayoutExamplesRoute,
    DashboardDashboardLayoutProfileRoute: DashboardDashboardLayoutProfileRoute,
    DashboardDashboardLayoutIndexRoute: DashboardDashboardLayoutIndexRoute,
    DashboardDashboardLayoutPostsPostIdRoute:
      DashboardDashboardLayoutPostsPostIdRoute,
    DashboardDashboardLayoutPostsNewRoute:
      DashboardDashboardLayoutPostsNewRoute,
    DashboardDashboardLayoutPostsIndexRoute:
      DashboardDashboardLayoutPostsIndexRoute,
  }

const DashboardDashboardLayoutRouteWithChildren =
  DashboardDashboardLayoutRoute._addFileChildren(
    DashboardDashboardLayoutRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardDashboardLayoutRoute: typeof DashboardDashboardLayoutRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardLayoutRoute: DashboardDashboardLayoutRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SettingsSettingsLayoutRouteChildren {
  SettingsSettingsLayoutAuthenticationRoute: typeof SettingsSettingsLayoutAuthenticationRoute
  SettingsSettingsLayoutProfileRoute: typeof SettingsSettingsLayoutProfileRoute
  SettingsSettingsLayoutShortcutsRoute: typeof SettingsSettingsLayoutShortcutsRoute
  SettingsSettingsLayoutTeamsRoute: typeof SettingsSettingsLayoutTeamsRoute
  SettingsSettingsLayoutIndexRoute: typeof SettingsSettingsLayoutIndexRoute
}

const SettingsSettingsLayoutRouteChildren: SettingsSettingsLayoutRouteChildren =
  {
    SettingsSettingsLayoutAuthenticationRoute:
      SettingsSettingsLayoutAuthenticationRoute,
    SettingsSettingsLayoutProfileRoute: SettingsSettingsLayoutProfileRoute,
    SettingsSettingsLayoutShortcutsRoute: SettingsSettingsLayoutShortcutsRoute,
    SettingsSettingsLayoutTeamsRoute: SettingsSettingsLayoutTeamsRoute,
    SettingsSettingsLayoutIndexRoute: SettingsSettingsLayoutIndexRoute,
  }

const SettingsSettingsLayoutRouteWithChildren =
  SettingsSettingsLayoutRoute._addFileChildren(
    SettingsSettingsLayoutRouteChildren,
  )

interface SettingsRouteChildren {
  SettingsSettingsLayoutRoute: typeof SettingsSettingsLayoutRouteWithChildren
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSettingsLayoutRoute: SettingsSettingsLayoutRouteWithChildren,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TosRoute: TosRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiTrpcSplatServerRoute: ApiTrpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
